name: CI

#on:
  #pull_request:
    #branches: [ master ]
on:
  push:
    branches:
      - feature/add-test-action

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
